# Generated by Django 3.2.8 on 2021-11-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=40, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=40, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
