# Generated by Django 3.2.8 on 2021-11-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211103_0901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProducdtImage',
            new_name='ProductImage',
        ),
    ]
